CREATE (sofia:Person{id:"Sofia", city: "Rome", age: 21})
CREATE (chiara:Person{id:"Chiara", city: "Rome", age: 25})
CREATE (fabio:Person{id:"Fabio", city: "Milan", age: 19})
CREATE (luca:Person{id:"Luca", city: "Rome", age: 24})
CREATE (dress:Item{id:"dress", price: 75, colour: "blue"})
CREATE (suit:Item{id:"suit", price: 80, colour: "black"})
CREATE (shirt:Item{id:"shirt", price: 30, colour: "white"})
CREATE (jeans:Item{id:"jeans", price: 40, colour: "blue"})
CREATE (tshirt:Item{id:"tshirt", price: 15, colour: "white"})
CREATE (formal:Category{id:"formal"})
CREATE (casual:Category{id:"casual"})

CREATE (sofia)-[:Follow]->(luca)
CREATE (sofia)-[:Follow]->(fabio)
CREATE (fabio)-[:Follow]->(luca)
CREATE (luca)-[:Follow]->(chiara)
CREATE (sofia)-[:Buy]->(dress)
CREATE (sofia)-[:Buy]->(dress)
CREATE (sofia)-[:Buy]->(shirt)
CREATE (sofia)-[:Buy]->(suit)
CREATE (chiara)-[:Buy]->(dress)
CREATE (chiara)-[:Buy]->(shirt)
CREATE (fabio)-[:Buy]->(suit)
CREATE (luca)-[:Buy]->(jeans)
CREATE (luca)-[:Buy]->(jeans)
CREATE (luca)-[:Buy]->(tshirt)
CREATE (chiara)-[:Recommend]->(suit)
CREATE (chiara)-[:Recommend]->(shirt)
CREATE (fabio)-[:Recommend]->(jeans)
CREATE (fabio)-[:Recommend]->(shirt)
CREATE (dress)-[:Of]->(formal)
CREATE (suit)-[:Of]->(formal)
CREATE (shirt)-[:Of]->(formal)
CREATE (jeans)-[:Of]->(casual)
CREATE (tshirt)-[:Of]->(casual)
CREATE (shirt)-[:Of]->(casual);
